version: "3"
services:
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./src:/go/src
    tty: true
    env_file:
      - ./.go_env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8000:8080"
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: todo-mysql-db
    tty: true
    ports:
      - "3306:3306"
    env_file: ./.db_env
    volumes:
      - ./src/infrastructure/sql/data:/var/lib/mysql
      - ./src/infrastructure/sql/myconf/my.cnf:/etc/mysql/conf.d/my.cnf
